### ISSUE TITLE
Live Refresh

### ISSUE THREAD

**Issue by eladavron** [TextAnalysisTool/Releases#61] opened 2019-01-24 15:27 UTC
A lot of text editors support live-refresh of files when they're modified by another source. I think it will be super helpful in this program, given how it's used a lot for log parsing, and sometimes those logs are "live" and having to hit "refresh" manually all the time is a bit unproductive.

**Comment by vincec-msft** [comment] 2019-01-24 15:28
Duplicate of #7

**Closed by vincec-msft** 2019-01-24 15:28 UTC
