### ISSUE TITLE
Creating Master and Subfilter in TextAnalysisTool

### ISSUE THREAD

**Issue by egiklny** [TextAnalysisTool/Releases#85] opened 2020-07-22 12:48 UTC
Hi Gitbub team,

Thanks for this wonderful tool "TextAnalysisTool". I have been using it since 5 years and its really nice and helped in increasing my work efficiency. 

Currently while using this tool for different type of work we have defined different filter and continuously maintaining them.

I have an optimization wherein in filter if we can create a master filter checkbox and then subfilter checkbox.

Now suppose if somebody is using 10 types of filter , one can save a single filter file only . Once he load the filter file on particular txt file he/she can enable the respective master filter only.

Issue with enabling all filter in one go is system can hang depending upon filter size.

regards,
Sumit

**Comment by DavidAnson** [comment] 2020-07-22 15:21
This sounds like a duplicate of issue #2.

**Closed** 2020-12-18 02:56 UTC
