### ISSUE TITLE
TextAnalysisTool.net for ubuntu machine

### ISSUE THREAD

**Issue by singhalgk** [TextAnalysisTool/Releases#46] opened 2017-09-11 13:02 UTC
Could you please provide a version to run on ubuntu machine. I am very much dependent on this tool now. but I don't have windows machine anymore.

**Comment by DavidAnson** [comment] 2017-09-11 16:35
The most practical way to do that would be to port to .NET Core which is the .NET support story for Linux. However, that team does not plan to support WinForms: https://github.com/dotnet/core/issues/374

**Comment by zholobov** [comment] 2017-09-11 16:41
@DavidAnson do you know if it's possible to do any other UI on .NET Core? From the link you mentioned it looks like no, but just in case...

**Comment by zholobov** [comment] 2017-09-11 16:44
I'm asking because I'm still interested in improving this awesome tool, and I would like to help in making it cross-platform somehow.

**Comment by vincec-msft** [comment] 2017-09-11 17:10
About a year ago I tried running on Mono, but ran into a Mono bug that I didn't have time to track down. just in case someone was thinking of that route.

**Comment by singhalgk** [comment] 2017-09-12 06:37
I have already tried running this tool with mono. Textanalysistool launched properly. but It doesnot disaply text after loading the file. I am very much struggling to somehow run it on ubuntu  machine.

**Comment by DavidAnson** [comment] 2020-12-18 03:02
Duplicate of #19

**Closed by DavidAnson** 2020-12-18 03:02 UTC
Labels: enhancement
