### ISSUE TITLE
Have to save filter every time open it from command line？

### ISSUE THREAD

**Issue by cloudseasail** [TextAnalysisTool/Releases#40] opened 2016-11-17 05:03 UTC
when loading filters using command line,  it always ask me to save the filter., but I didnot modify the filter, it is quite ignoring.
`270 TextAnalysisTool.NET.exe \Logs\MyLog.log /Filters:"\Saved Filters\MyFilters.tat"`

"Load Filter" using UI menu donot have this issue.

**Comment by DavidAnson** [comment] 2016-11-17 05:14
Sounds like a duplicate of issue #39 - the change discussed there is under review now. Thanks for letting us know!

**Closed by DavidAnson** 2016-11-17 05:14 UTC

**Comment by vincec-msft** [comment] 2016-11-17 15:25
I can only reproduce this if the filters are somehow changed. Are you toggling the enabled state, moving, or editing the filters? If so then it's issue #39 as David suggests. If you run the command above and immediately close the app yet you still get a prompt to save then it's a different issue and we'll need more detail in order to reproduce.
