### ISSUE TITLE
ctrl N reports an error on the new version

### ISSUE THREAD

**Issue by moroal** [TextAnalysisTool/Releases#103] opened 2023-04-10 07:19 UTC
![image](https://user-images.githubusercontent.com/14798296/230848786-343b407d-bddf-45d0-aa8e-b88a19a63d98.png)

**Comment by vincec-msft** [comment] 2023-04-10 14:18
I cannot reproduce this issue. Can you give more information to help repro? Does it happen when certain lines are selected? On all files? When the window is on a virtual desktop? What's unique about your setup that might narrow down the circumstances for this error?

It's possible that your registry is corrupted. Try replacing the FilterDialogWidth value with something new:
reg add HKEY_CURRENT_USER\Software\DavidAns\TextAnalysisTool.NET /v FilterDialogWidth /t REG_DWORD /d 700

**Comment by moroal** [comment] 2023-04-12 03:16
![image](https://user-images.githubusercontent.com/14798296/231339442-fde8b5f4-864f-46bf-821a-93752ac8f058.png)

**Comment by caixinyuan** [comment] 2023-04-13 04:39
I encountered the same error on Win11

**Comment by vincec-msft** [comment] 2023-04-13 14:23
@moroal , @caixinyuan , please try this version:
[TextAnalysisTool.NET.zip](https://github.com/TextAnalysisTool/Releases/files/11223140/TextAnalysisTool.NET.zip)

Try both Ctrl+N and Ctrl+F to make sure both dialogs work.

**Comment by caixinyuan** [comment] 2023-04-14 02:28
> @moroal，@caixinyuan，请尝试此版本：[TextAnalysisTool.NET.zip](https://github.com/TextAnalysisTool/Releases/files/11223140/TextAnalysisTool.NET.zip)
> 
> 尝试按 Ctrl+N 和 Ctrl+F 以确保两个对话框都正常工作。

It's good

**Comment by moroal** [comment] 2023-04-14 07:06
> @moroal , @caixinyuan , please try this version: [TextAnalysisTool.NET.zip](https://github.com/TextAnalysisTool/Releases/files/11223140/TextAnalysisTool.NET.zip)
> 
> Try both Ctrl+N and Ctrl+F to make sure both dialogs work.

it's work, thank you

**Comment by DavidAnson** [comment] 2023-04-14 19:24
Thanks a bunch, @vincec-msft! I'll coordinate on a patch release next week!

**Comment by vincec-msft** [comment] 2023-04-25 18:31
Fixed in the 2023-04-25 release.

**Closed by vincec-msft** 2023-04-25 18:31 UTC
Labels: bug
