### ISSUE TITLE
When I double-click on a line of text, an exception occurs

### ISSUE THREAD

**Issue by tianke3477** [TextAnalysisTool/Releases#105] opened 2023-04-23 09:16 UTC
version 2023-03-24

When I double-click on a line of text, I get the following message and the application exit.

![image](https://user-images.githubusercontent.com/613854/233830561-de215eb3-2298-482d-9f43-7e54f24f1fc1.png)

**Comment by vincec-msft** [comment] 2023-04-23 15:21
Duplicate of #103

**Closed by vincec-msft** 2023-04-23 15:21 UTC
