### ISSUE TITLE
Add a refresh button or the ability to monitor active log files

### ISSUE THREAD

**Issue by linuxgurugamer** [TextAnalysisTool/Releases#88] opened 2020-11-22 17:59 UTC

**Comment by DavidAnson** [comment] 2020-11-22 18:06
`File | Reload` or `F5` reload the current file.

**Comment by linuxgurugamer** [comment] 2020-11-23 15:58
Thank you, the F5 will work for now.  I'm using this to monitor a log file in real time, would be very helpful if it could someday watch an active log file

**Comment by vincec-msft** [comment] 2020-11-23 17:20
Dupe of #7 ?

**Comment by DavidAnson** [comment] 2020-11-23 17:59
Agreed, thanks @vincec-msft.

**Closed by DavidAnson** 2020-11-23 17:59 UTC
Labels: enhancement
