### ISSUE TITLE
garbled

### ISSUE THREAD

**Issue by moroal** [TextAnalysisTool/Releases#93] opened 2021-06-30 02:14 UTC
How to solve Chinese garbled, please help me, thank u.

**Comment by moroal** [comment] 2021-06-30 02:15
362 name:寰  packagename:com.tencent.weishi  version:8.26.1.588
just like this

**Comment by DavidAnson** [comment] 2021-06-30 02:25
Make sure the file begins with a BOM so any Unicode characters are interpreted correctly. Maybe experiment with the font also?

https://en.m.wikipedia.org/wiki/Byte_order_mark

**Comment by vincec-msft** [comment] 2021-06-30 03:38
Duplicate of #58

**Closed** 2021-08-03 16:45 UTC
Labels: question
